### PR TITLE
Switch to github actions

### PR DESCRIPTION
**Pull request by gavv**
See #37 for rationale.

On github actions, hardware acceleration is supported only on macos workers, but not on linux workers. On the other hand, hardware acceleration on macos doesn't use kvm (obviously). It means that we can't use our `env-android` docker image to run instrumented tests on github actions, because there is no `/dev/kvm` on host.

To deal with it, I've reworked CI scripts. There are 4 groups of CI jobs:

* native linux build - uses scripts from `scripts/linux`;
* native osx build - uses scripts from `scripts/osx`;
* android build on macOS -  uses scripts from `scripts/android` directly; relies on github actions to install android components; runs instrumented tests;
* android build on Linux - uses `scripts/android_docker.sh`, which in turn runs scripts from `scripts/android` inside `env-android` image; relies on `env-android` to install android components; doesn't run instrumented tests.

`scripts/android_docker.sh` is intended to be used both on CI and locally. It supports three commands: `build`, `test`, and `clean`. Only `build` command is used on CI.

This script supports incremental builds. Each of the following heavy actions will be performed only once:

* pull docker image
* create container
* download android components
* build roc toolkit
* create AVD

If you run the script multiple times, it will only re-build java part and re-run tests and skip other actions. On the other hand, if you've changed some parameters (e.g. `JAVA_VERSION` or `API`), it will automatically re-run necessary steps.

Since these scripts are not only for CI, but for users and developers too, I've moved them from `scripts/ci` to just `scripts` and documented their usage in README.

Also, I've moved `device.sh` script from `env-docker` to `roc-java`, because now we use it outside of the docker image too - from macos job in github actions. And I've reworked it's argument parsing part because it didn't work on bash from macOS (it has different getopt implementation).

Here's how the new CI will look like: https://github.com/gavv/roc-java/actions/runs/758719810

And here is the new README: https://github.com/gavv/roc-java

### CODE REVIEW

**Comment by gavv** [comment]
Forgot to mention: I did NOT try to migrate bintray support to github actions because of #36.

**Comment by MatteoArella** [comment]
I'm really sorry for my long absence but unfortunately I've had no time to work on this. Awesome work LGTM! :)

**Review by MatteoArella — APPROVED** [review]

**Comment by ortex** [comment]
LGTM!

**Review by ortex — APPROVED** [review]

**Comment by gavv** [comment]
@MatteoArella no problem, you're welcome. Merging this.

**Pull request merged**
