### PR TITLE
PR for issue #101: Remove getValue from all enums

### PR DESCRIPTION
**Pull request by PoulasthaMukherjee**
Numeric value of enum is actually not needed outside of roc-java package.

- remove `getValue` method from all enums [done]
- convert `value` field of all enums from private to package-private [done]
- use `value` instead of `getValue` everywhere inside roc-java [done]

### CODE REVIEW

**Comment by ortex** [comment]
Hi @PoulasthaMukherjee, thanks for PR. 

Within this task changes are supposed only in enum classes: 

 - RocLogLevel
 - ResamplerBackend
 - Protocol
 - PacketEncoding
 - Interface
 - FrameEncoding
 - FecEncoding
 - ClockSource
 - ChannelSet
 - ResamplerProfile

Please revert all irrelevant changes

**Comment by PoulasthaMukherjee** [comment]
@ortex Is the rest okay?

**Comment by ortex** [comment]
also, you delete `final` modificator from some enums, need to revert.

Everything else looks good. Will make a final review after the changes

**Comment by PoulasthaMukherjee** [comment]
Okay. Can you give me until tomorrow? I'll commit again.

**Comment by ortex** [comment]
Yeah, of course, no hurry

**Comment by PoulasthaMukherjee** [comment]
@ortex Do you want me to remove `final` modificator from all enums?

**Comment by PoulasthaMukherjee** [comment]
@ortex Oh I'm so sorry. I think I accidentally removed `final` from `ClockSource.java` and `RocLogLevel.java`. I think the rest of the files aren't changed that way. I've reverted those changes back.

**Comment by PoulasthaMukherjee** [comment]
@ortex Have you reviewed the changes? I'd like to know if the PR is worth merging.

**Comment by ortex** [comment]
PR is worth merging

Please, delete `getValue` from followed enums as well:

 - ChannelSet
 - FecEncoding
 - FrameEncoding
 - RocLogLevel

**Comment by gavv** [comment]
Side note. The number of commits is insane. Please don't create individual commit for every micro change. It creates a lot of noise in github and email notifications.

**Comment by PoulasthaMukherjee** [comment]
@gavv I'm so sorry. I'll keep that in mind.

**Comment by ortex** [comment]
> @ortex I did remove that from those enums. Are there any left in those files that I might have missed?

You didn't. 
e.g. https://github.com/PoulasthaMukherjee/roc-java/blob/main/src/main/java/org/rocstreaming/roctoolkit/ChannelSet.java#L20-L22

**Comment by PoulasthaMukherjee** [comment]
@ortex on it

**Comment by PoulasthaMukherjee** [comment]
@ortex I have changed it

**Comment by ortex** [comment]
Merged. Thanks

**Comment by PoulasthaMukherjee** [comment]
@ortex Thank you. Could you put the GSSOC23 label on this issue as well?

**Pull request merged**
