### PR TITLE
use jul logger by default

### LINKED ISSUE #3: Use standard Java logger by default
Currently, if `Logger.setCallback()` was never called, or it was called with `null` argument, we use "default logger".

Currently, default logger is implemented in libroc (native code), and it just writes message to stderr.

It would be more convenient to implement default logger in java and make it writing to standard java logger instead of stderr.

We should make sure than on android, default logger will send logs to android log (which can be received with adb logcat).

### PR DESCRIPTION
**Pull request by ortex**
fix #3

### CODE REVIEW

**Comment by gavv** [comment]
Three questions:

1. We call setCallback during initialization, so by default we use jul logger. But, if the user will set some logger calbback manually, and then will revert it to default by calling setCallback(null), we will use native default logger instead of jul logger, right? I think it should be fixed.

2. mapLogLevel can throw exception. Is native code that invokes callback ready for exceptions? Maybe better fallback to some specific log level instead of throwing?

    * BTW, if native code is not read for exceptions, I think we should modify setCallback to suppress exceptions for user-provided callback? E.g. by wrapping in on java side.

3. In the issue we have this part: `We should make sure than on android, default logger will send logs to android log (which can be received with adb logcat).` Is it true now with using jul?

**Comment by ortex** [comment]
@gavv 
1. Agreed
2. Yeah, we can fallback to some level. Which one? Error? 
3. Yeah, that should be true

> BTW, if native code is not ready for exceptions, I think we should modify setCallback to suppress exceptions for user-provided callback? E.g. by wrapping in on java side.

or we can add supporting on JNI leve, e.g:
```
    env->CallVoidMethod(handler_args.callback, handler_args.methID, levelObj, jmodule, jmess);
    if (env->ExceptionCheck()) {
        env->ExceptionDescribe(); // print exception to stderr
        env->ExceptionClear();
    }
```

**Comment by gavv** [comment]
2. Yep, I think log error is good fallback.

3. Support at jni level is even better,  agree.

**Comment by gavv** [comment]
Probably printing exception to stderr is not great - user may want to disable stderr, or maybe user doesn't have stderr, e.g. on android.

Maybe better print exception to jul?

**Comment by gavv** [comment]
Maybe rename setCallback0 to setCallbackImp or setCallbackImpl or setCallbackNative?

**Comment by gavv** [comment]
Consider reworking TestValidLoggerSetLevel to be synchronous (wait for actual logs).

**Pull request merged**
