### PR TITLE
Update git URLs

### PR DESCRIPTION
**Pull request by gavv**
See details here: #22

### CODE REVIEW

**Comment by MatteoArella** [comment]
LGTM! :+1:

**Comment by gavv** [comment]
@MatteoArella BTW feel free to merge my PRs if you approve them.

**Comment by MatteoArella** [comment]
> @MatteoArella BTW feel free to merge my PRs if you approve them.

I wasn't able to do it for unauthorized reasons

**Comment by gavv** [comment]
Damn, you disappeared from the list in settings for some reason. Maybe after rename... Sorry. re-added.

**Pull request merged**
